#!/bin/bash
# One-command installer for the self-hosted analytics stack.
# Idempotent: safe to re-run. Generates real secrets on first run,
# re-uses the existing .env on subsequent runs.
#
# Flags:
#   --fresh    Ignore any existing pre-rename volumes and install clean.
#   --upgrade  Print migration instructions and exit. Does NOT migrate
#              automatically. See UPGRADING.md.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!!\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31mxxx\033[0m %s\n' "$*" >&2; exit 1; }

print_help() {
  cat <<'HELP'
Usage: ./install.sh [--fresh|--upgrade|--help]

One-command installer for the self-hosted analytics stack.
Idempotent: safe to re-run. Generates real secrets on first run,
re-uses the existing .env on subsequent runs.

Flags:
  --fresh    Ignore any existing pre-rename volumes and install clean.
  --upgrade  Print migration instructions and exit. Does NOT migrate
             automatically. See UPGRADING.md.
  --help     Print this help.
HELP
}

FLAG_FRESH=0
FLAG_UPGRADE=0
for arg in "$@"; do
  case "$arg" in
    --fresh)   FLAG_FRESH=1 ;;
    --upgrade) FLAG_UPGRADE=1 ;;
    -h|--help) print_help; exit 0 ;;
    *) die "Unknown flag: $arg (see --help)" ;;
  esac
done

# --upgrade short-circuits everything else. It's pure docs.
if (( FLAG_UPGRADE == 1 )); then
  cat <<EOF
See UPGRADING.md for migration instructions.
Quick summary of the two supported paths:

  1. Preserve data:
     - Keep your old volumes as-is.
     - Add a docker-compose.upgrade.yml override that maps the new
       named volumes to the old globally-named ones.
     - Example is in UPGRADING.md.

  2. Start fresh (destroys existing data):
     - Back up first:   ./scripts/backup.sh
     - Remove old:      docker volume rm postgres_data n8n_data prefect_data
     - Install clean:   ./install.sh --fresh
EOF
  exit 0
fi

# ---------- preflight ----------
command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || die "Docker daemon is not running."
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "docker compose (v2) or docker-compose (v1) is required."
fi
command -v openssl >/dev/null 2>&1 || die "openssl is required for secret generation."

# ---------- detect pre-rename volumes (data-loss guard) ----------
# Older revisions of this repo used globally-named external volumes
# (postgres_data, n8n_data, prefect_data). This branch renamed them to
# ${COMPOSE_PROJECT_NAME}_*. Running 'docker compose up -d' after a git
# pull would silently create fresh empty volumes and the user would
# think their data vanished. Detect the old ones and refuse to proceed
# unless the operator explicitly says "fresh" or follows UPGRADING.md.
OLD_VOLUMES=()
for v in postgres_data n8n_data prefect_data; do
  if docker volume inspect "$v" >/dev/null 2>&1; then
    OLD_VOLUMES+=("$v")
  fi
done

if (( ${#OLD_VOLUMES[@]} > 0 )) && (( FLAG_FRESH == 0 )); then
  cat >&2 <<EOF
================================================================
WARNING: found pre-rename data volumes on this machine:
  ${OLD_VOLUMES[*]}

These look like data from an earlier version of this stack, before
volumes were renamed to \${COMPOSE_PROJECT_NAME}_*. If you continue
with a default install, you will get FRESH EMPTY volumes and your
existing n8n workflows / Prefect state / Postgres data will appear
to have vanished (the old volumes stay on disk but unreferenced).

Read UPGRADING.md in this repo for the two supported paths:
  1. Keep your data by pointing the new stack at the old volume names.
  2. Start fresh and restore from a pg_dumpall backup.

If you know what you're doing and want to install fresh anyway,
re-run with:
  ./install.sh --fresh
================================================================
EOF
  exit 2
fi

# ---------- directories ----------
say "Creating data directories"
mkdir -p backups shared

# ---------- secrets ----------
if [[ -f .env ]]; then
  say "Reusing existing .env (delete it to regenerate secrets)"
else
  say "Generating .env with fresh secrets"
  POSTGRES_PASSWORD="$(openssl rand -base64 32 | tr -d '=+/' | head -c 32)"
  N8N_ENCRYPTION_KEY="$(openssl rand -hex 32)"

  cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do NOT commit this file. Re-generate by deleting .env and re-running install.sh.

COMPOSE_PROJECT_NAME=sha

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_USER=admin
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=analytics
POSTGRES_N8N_DB=n8n
POSTGRES_METABASE_DB=metabase
POSTGRES_PREFECT_DB=prefect

N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

TZ=UTC
EOF
  chmod 600 .env
fi

# ---------- bring up the stack ----------
say "Starting stack (this may take a few minutes on first run)"
$COMPOSE up -d

# ---------- wait for health ----------
# name    = display label shown to the user
# service = compose service name (used to compose log hints)
# url     = health endpoint to poll
# max     = number of polling iterations (2s apart)
wait_for() {
  local name="$1" service="$2" url="$3" max="${4:-60}" i=0
  say "Waiting for $name ($url)"
  while (( i < max )); do
    if curl -fsS -o /dev/null "$url"; then
      printf '    %s is up\n' "$name"
      return 0
    fi
    sleep 2
    i=$(( i + 1 ))
  done
  warn "$name did not become healthy within $(( max * 2 ))s. Check: $COMPOSE logs $service"
  return 1
}

failed_services=()
wait_for "n8n"      "n8n"      "http://localhost:5678/healthz"    120 || failed_services+=("n8n")
wait_for "Metabase" "metabase" "http://localhost:3000/api/health" 120 || failed_services+=("metabase")
wait_for "Prefect"  "prefect"  "http://localhost:4200/api/health" 120 || failed_services+=("prefect")

if (( ${#failed_services[@]} > 0 )); then
  echo
  echo "================================================================"
  printf 'Install FAILED. These services did not become healthy: %s\n' "${failed_services[*]}"
  echo
  echo "Diagnose with:"
  for svc in "${failed_services[@]}"; do
    echo "  $COMPOSE logs $svc"
  done
  echo
  echo "Stack is left running so you can inspect it."
  echo "Tear down with:  $COMPOSE down -v"
  echo "================================================================"
  exit 1
fi

# ---------- summary ----------
cat <<EOF

================================================================
Self-Hosted Analytics Stack is running.

  n8n        http://localhost:5678
  Metabase   http://localhost:3000
  Prefect    http://localhost:4200
  Postgres   localhost:5432  (user: admin)

Credentials are in .env (chmod 600, gitignored).

Next:
  1. Open each URL and create your admin account.
  2. In Metabase, connect to postgres:5432 / database 'analytics'.
  3. See examples/ for end-to-end pipeline templates.

To stop:      $COMPOSE stop
To remove:    $COMPOSE down
To backup:    ./scripts/backup.sh
================================================================
EOF
