#!/bin/bash
# One-command installer for the self-hosted analytics stack.
# Idempotent: safe to re-run. Generates real secrets on first run,
# re-uses the existing .env on subsequent runs.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!!\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31mxxx\033[0m %s\n' "$*" >&2; exit 1; }

# ---------- preflight ----------
command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || die "Docker daemon is not running."
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "docker compose (v2) or docker-compose (v1) is required."
fi
command -v openssl >/dev/null 2>&1 || die "openssl is required for secret generation."

# ---------- directories ----------
say "Creating data directories"
mkdir -p backups shared

# ---------- secrets ----------
if [[ -f .env ]]; then
  say "Reusing existing .env (delete it to regenerate secrets)"
else
  say "Generating .env with fresh secrets"
  POSTGRES_PASSWORD="$(openssl rand -base64 32 | tr -d '=+/' | head -c 32)"
  N8N_ENCRYPTION_KEY="$(openssl rand -hex 32)"

  cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do NOT commit this file. Re-generate by deleting .env and re-running install.sh.

COMPOSE_PROJECT_NAME=sha

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_USER=admin
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=analytics
POSTGRES_N8N_DB=n8n
POSTGRES_METABASE_DB=metabase
POSTGRES_PREFECT_DB=prefect

N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

TZ=UTC
EOF
  chmod 600 .env
fi

# ---------- bring up the stack ----------
say "Starting stack (this may take a few minutes on first run)"
$COMPOSE up -d

# ---------- wait for health ----------
wait_for() {
  local name="$1" url="$2" max="${3:-60}" i=0
  say "Waiting for $name ($url)"
  while (( i < max )); do
    if curl -fsS -o /dev/null "$url"; then
      printf '    %s is up\n' "$name"
      return 0
    fi
    sleep 2
    i=$(( i + 1 ))
  done
  warn "$name did not become healthy within $(( max * 2 ))s. Check: $COMPOSE logs $name"
  return 1
}

wait_for "n8n"      "http://localhost:5678/healthz"        120 || true
wait_for "metabase" "http://localhost:3000/api/health"     120 || true
wait_for "prefect"  "http://localhost:4200/api/health"     120 || true

# ---------- summary ----------
cat <<EOF

================================================================
Self-Hosted Analytics Stack is running.

  n8n        http://localhost:5678
  Metabase   http://localhost:3000
  Prefect    http://localhost:4200
  Postgres   localhost:5432  (user: admin)

Credentials are in .env (chmod 600, gitignored).

Next:
  1. Open each URL and create your admin account.
  2. In Metabase, connect to postgres:5432 / database 'analytics'.
  3. See examples/ for end-to-end pipeline templates.

To stop:      $COMPOSE stop
To remove:    $COMPOSE down
To backup:    ./scripts/linux/backup.sh
================================================================
EOF
